### ISSUE TITLE
Can't run tilix after building from source

### ISSUE THREAD

**Issue by Mike-Now** [gnunn1/tilix#1018]
After building from source I get an error:

```
2017-07-16T21:04:03.621:resource.d:findResource:53 Resource tilix/resources/tilix.gresource could not be found

(tilix:12548): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Tilix.Keybindings' is not installed
```

It would be nice if the README file covered the necessary steps after building to start the application.

**Comment by gnunn1** [comment]
Looks like you missed the step to run install.sh as per the README which says this after building:

```
The application depends on various resources to function correctly, run sudo ./install.sh to build and copy all of the resources to the correct locations. Note this has only been tested on Arch Linux, use with caution.
```

**Comment by shinenelson** [comment]
I ran into the same issue even after running `install.sh`. Though I was smart enough to read the code of the script to find that I could pass an argument to set `PREFIX` to a custom directory than `/usr` (that could be mentioned in the `README` too).

I tried 3 different options on 3 isolated bare VMs : 
1. With the default option for `PREFIX` installing to `/usr` (and with `sudo` privileges)
2. Installing to `$HOME/.local` (`PREFIX=$HOME/.local`) (without `sudo` privileges)
3. Installing to custom build directory (`PREFIX=build`) (without `sudo` privileges; within the same directory as the cloned repository) and then adding the `build` directory to my `PATH`.
None of the above options worked for me.

I read through the `install.sh` script and the script looks to be installing the application correctly. I verified that the above mentioned file that is not found is indeed there in the exact same location that the binary says is not found.

I looked at the `data/resources/tilix.gresource.xml` file that generates `data/resources/tilix.gresource`. It has no mention of `com.gexperts.Tilix.Keybindings`. Could it be that the source code isn't compiling the Keybindings properly?

Or maybe the binary is looking for a different location than the location the file is in?

What could be the actual reason? I'm not familiar with D to dig into the source code to find the bug here. Otherwise, I'd be happy to help in any way I could.

**Comment by gnunn1** [comment]
The keybindings are not managed by the resource file but by the schema file which is installed separately. What was the output of install.sh, were any errors shown?

A common problem is not having the tool to compile the resources file installed.

Also for running tilix I've only tested it with installing it to ```\usr```. Not sure if it would being installed elsewhere, however if you get it working I'd be more then happy to take a PR for it.

**Comment by shinenelson** [comment]
Thank you for the pointer regarding the glib schema @gnunn1. So, I've been able to run the terminal fine with just a warning about VTE and no **FATAL** errors or segmentation faults / traps. All I had to do is re-compile the glib schemas into the `/usr` directory (I wonder why it didn't work in my initial `/usr` installation test VM :thinking:; Probably a permission issue or something).

So, if someone had to use custom directories (as argument `$1` to the `install.sh` script), they'd have to manually compile the glib schemas. Other than that, everything else works fine. I'll make a pull request with this update to the README and modification in the `install.sh` script in a while.

Aside : I have a minor UI issue or a transparent bar for the tabs (but that could just be me with all my heavy customizations to my final install). I'll just put it out here for the record.

**Comment by gnunn1** [comment]
If you have transparent terminal titles it means that tilix isn't picking up the resource file. If you run tilix from another terminal it should show some errors about this on the console.

**Comment by Mike-Now** [comment]
To run custom local build all you have to do is update your XDG_DATA_DIRS env variable to include the
$PREFIX/share path. I also had to remove system-wide tilix installation because there was probably a schema conflict.

@shinenelson please update your changes in wiki and pull request to reflect the XDG_DATA_DIRS solution.

**Comment by shinenelson** [comment]
Damn! Why didn't I think of hitting `man glib-compile-schemas` before doing all this? :thinking: 

Good find @Mike-Now. :ok_hand: 

I guess now all we have to do here is to get the users to append `$PREFIX/share` to their `XDG_DATA_DIRS` on shell invocation (i.e., `.bashrc`, `.zshrc`, etc) and all will be good.

**Comment by shinenelson** [comment]
Just a heads up here. If you're installing tilix to a custom directory and appending `$PREFIX/share` to `$XDG_DATA_DIRS` as mentioned in https://github.com/gnunn1/tilix/pull/1020#issuecomment-315649501, you'd need to make sure that `XDG_DATA_DIRS` are initialized during Xsession initialization. Otherwise, Tilix wouldn't run out of the Applications menu. It would work fine when invoked from a terminal (because you're probably going to be appending `$PREFIX/share` to `$XDG_DATA_DIRS` during your shell intialization and not Xsession initialization), but it wouldn't work from the Applications Menu.

I spent the last 3 days trying to figure the problem out ( what sense did `kernel: traps: tilix[<pid>] trap int3 ip:xxxxxxxxxxxx sp:xxxxxxxxxxxx error:0` really make? ).
The issue is because `dbus` initializes the `XDG_DATA_DIRS` environment variable during Xsession initialization.
I got the heads up (idea) from a freedesktop mailing list [post](https://lists.freedesktop.org/archives/dbus/2016-July/016960.html) with a similar issue related to `dbus`.

You could approach this in 2 different ways (both require `sudo` privileges anyway) : 
1. You provide `sudo` privileges during install; and let `glib-compile-schema` install the `tilix.gresource` install to the main list of `gschema`.
2. You could be a hacker and add `$PREFIX/share` to your Xsession initialization in `/etc/X11/Xsession.d/60x11-common_xdg_path`. (Any file in `/etc/X11/Xsession.d/` would seem to be fine, but this file seems to be the most appropriate as it does exactly that - initialize the `XDG_DATA_DIRS` environment variable)
