### ISSUE TITLE
Options for toggling quake-mode window

### ISSUE THREAD

**Issue by KSXGitHub** [gnunn1/tilix#1026]
### How should it works?

The following command should hide quake window if it is shown and display it otherwise

```sh
tilix --toggle-quake-window
```
### Why?

I've set a keybinding (<kbd>Super + R</kbd>) to open quake terminal and make quake terminal hides when lost focus. The problem is, when I press <kbd>Super + R</kbd> inside the terminal, it disappears and re-appears.

**Comment by gnunn1** [comment]
There's no option ```--toggle-quake-window```, it's just ```--quake```.

Also when using the hide when lost focus option you may need to increase the timing with the ```Delay hiding window``` option to get it working properly.

![screenshot from 2017-07-20 07-39-59](https://user-images.githubusercontent.com/9358238/28415667-b49eef52-6d1e-11e7-83f3-d6ac97015c7f.png)

**Comment by gnunn1** [comment]
See #858 for more details.

**Comment by KSXGitHub** [comment]
@gnunn1 I already know there's a `--quake` option, but what it does is only showing, not hiding. I need an option that do both: Showing (when quake window is hidden) and Hiding (when quake window is shown).

**Comment by gnunn1** [comment]
The ```-quake``` option already toggles the window so when it is hidden it shows the window and when the window is showing it hides it. Your problem is the hide on lost focus option, if you turn that off you should see the toggling works fine.

If you want to use the hide on lost focus option you need to adjust the timing.
