### ISSUE TITLE
Can you set Tilix icon in top left corner of the top bar?

### ISSUE THREAD

**Issue by Pshemas** [gnunn1/tilix#1052]
I'm running Tilix on Centos 7 (ver 1.6.4 , thx to ivoarch_Tilix COPR repo). Is it possible to set Tilix to use system theme icon in top left top bar menu instead of default one? It is a minor annoyance, but I simply can't unsee it :D.
![tilix_toplefticon](https://user-images.githubusercontent.com/6144330/29024164-04f021a0-7b71-11e7-9df1-d283a8eb247a.jpeg)

**Comment by gnunn1** [comment]
Are you saying that Tilix is showing the icon whereas other aplications like gedit are not?

It's usually controlled by the gnome tweak tool in the Top Bar section, there is an option called "Show Application Menus" that controls it for all applications.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 I think he means to replace that icon with something else. Sadly this can not be done by the application. It's done by Gtk. I have already reported that upstream to use at least the symbolic icon if found https://bugzilla.gnome.org/show_bug.cgi?id=783217. They're willing to review/accept a patch if anybody has more experience with C/Gtk than me :)
The best behavior would be to be able to set that icon. Otherwise using just the symbolic icon would be really nice and would fit with the rest of symbolic ones

**Comment by gnunn1** [comment]
Thanks @bil-elmoussaoui, you are right that there is nothing I can do about that.
