### ISSUE TITLE
Tab-sidebar with previews

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1062]
I use Firefox with the Tab Center extension. There the sidebar shows previews (like the current Tilix-sidebar does, but permanent visible) until the list gets full – then the tabs are scaled and show only the title and an icon – without the preview. Here this behaviour is shown on the left side:

![](https://www.soeren-hentzschel.at/wp-content/uploads/tab-center-3.png)

Could this behaviour be implemented with the new tabs mode, so that the previews are shown (with or without the title) until the bar is full – and then it is switched to your current tabs sidebar design of your master branch?

I can even think of combining both modes like Firefox does: Here the tabs sidebar can be collapsed, so that only thumbnails are shown (like in the image below on the right side). This way Tilix can show either just the Number of the tab (like FF shows just the icons), or hide them like it does currently.

![](https://www.soeren-hentzschel.at/wp-content/uploads/tab-center-4.png)

**Comment by gnunn1** [comment]
I had considered a similar solution and it was discussed on the Improve UI issue. The basic problem is that making the sidebar permanently displayed as significant challenges in generating thumbnails in near real-time. Additionally, the compressed view which I also considered was feeling like too much like tabs that I might as well of just included tabs so that's the direction I went.

I appreciate the input but I'm not planning on re-visiting this again unless someone else wants to do the work.
