### ISSUE TITLE
Wrong size of quake mode with more screens

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1099]
I have an HD secondary screen left and an 3440x1440 main screen on the right side, with both screens aligned on the bottom. Opening Tilix Quake on the right screen works fine, but leads to the following artifact when opened on the left screen:

![29847625-f312b71e-8d1c-11e7-84e7-89267b0ddbed](https://user-images.githubusercontent.com/10520767/29847862-07c6922e-8d1e-11e7-91a0-b8df888a62ae.png)

Somehow the width of the window is doubled, but I have standard scaling on both screens, no UHD resolution!
What you see in the upper left corner is the space not visible on the screens, since the right one is taller than the left one.

**Comment by gnunn1** [comment]
Are you using Wayland, do you get the same behavior in X11?

**Comment by fbruetting** [comment]
Yes, Wayland. Haven’t tried X11 at work yet.

**Comment by gnunn1** [comment]
I can reproduce this under Wayland, if I try to open quake mode on a secondary monitor it ends up in the wrong position. Unfortunately I cannot fix it as this is due to the Wayland behaves, there is no way to set the screen coordinates.

I'm thinking of disabling quake mode under Wayland, there's just too many problems with it.
