### ISSUE TITLE
Menu Bar missing

### ISSUE THREAD

**Issue by huti26** [gnunn1/tilix#1107]
So this problem will sound rather stupid at first, but let me explain.
I'm on linux mint 18.1 and tried to configure tilix a bit. At some point I picked: 

Window Style: Disable CSD

This made the menu bar disapear. I then checked for a shortcut in order to get into the preferences, but after checking it on another device, it seems that by default this shortcut is disabled. Alright, so I tried to uninstall tilix in order to reset the config and just be smarter on next try, but it doesnt seem to work out. 

I used sudo apt-get --purge remove tilix and sudo apt-get --purge remove tilix-common, but everytime I reinstall the programm, the old config files are still used somehow. What exactly am I doing wrong?
Sorry if this seems like a rather simple problem, but after hours of googling I still can't fix it.

**Comment by bil-elmoussaoui** [comment]
You can use `tilix --preferences` in order to get to the preferences window. You can do that on whatever terminal you want ;) or use dconf editor to change the settings you want.
Using Dconf editor: 
Open Dconf editor and go to this path `/com/gexperts/Tilix/window-style` and change the `window-style` value to normal.
You can do that using your terminal too by typing ` gsettings set com.gexperts.Tilix.Settings window-style "normal"`
You must restart Tilix after doing that ;)

**Comment by gnunn1** [comment]
@bil-elmoussaoui covered this well, thanks.

**Comment by phw** [comment]
Just an addition because I have seen this misunderstanding for several applications: Uninstalling an application with the package manager will never touch your user configuration. The package manager is only concerned with the system level, it will not by itself touch any files in the user's home dir. This is by design.
