### ISSUE TITLE
Moving shells betweens windows of Tilix on KDE

### ISSUE THREAD

**Issue by leonekmi** [gnunn1/tilix#1142]
![image](https://user-images.githubusercontent.com/20224422/31194137-8044e716-a946-11e7-888c-fcf4080f20dd.png)
![image](https://user-images.githubusercontent.com/20224422/31194148-8ad460da-a946-11e7-85cc-134d7e060c6e.png)
The shell is in the middle of nowhere and cannot make it go (restart the entire session to fix). xkill does not recognize window.

**Comment by gnunn1** [comment]
Just to be clear, that screenshot shows what happens when you show the sidebar?

Does it happen with a different GTK theme like Adwaita?

Also note that I do not officially support Tilix on KDE, just Gnome and Unity. Hopefully I can guide you to a solution but I won't try to duplicate it in a KDE environment. Due to time constraints I need to limit what I can effectively support.

**Comment by leonekmi** [comment]
When i show the sidebar and moves a shell, if i release it in nowhere it will be stuck in the void.

**Comment by gnunn1** [comment]
I had a look at my code as I was thinking it might be an issue with the way I'm managing the dragImage but the issue I was suspecting had been addressed. I had this exact same issue when dragging terminals as the drag image needed to be explicitly freed, however I am doing this in the code.

To rule it out completely, you would compile from the source code. Once that is done, duplicate the issue,  click the hamburger menu and you will see a GC menu option. Click that a few times to force some garbarge collection to see if the drag image disappears.

**Comment by gnunn1** [comment]
@leonekmi Do you have time to look at this more and compile tilix from source?

**Comment by gnunn1** [comment]
No response from OP, closing.
