### ISSUE TITLE
Dead SSH connection hangs

### ISSUE THREAD

**Issue by bagage** [gnunn1/tilix#1145]
I'm not sure if that's a bug in Tilix, but since I hit that several times now I thought it would be good to at least report it. Feel free to close if irrelevant / not Tilix's fault :).

If I ssh to some remote server, and let it idle for some time (here 6 hours with laptop being closed / disconnected from wifi), once I go in Tilix again, the ssh session is still there but I cannot type anything and I cannot close it either (at least `ctrl+c` and `ctrl+d` are not working).
For now, my workaround is to split Tilix in two and close the ssh subwindow - but maybe Tilix should handle these broken connections?

```
$ uname -a 
Linux 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
$ tilix -v
Versions
	Tilix version: 1.6.4
	VTE version: 0.50
	GTK Version: 3.22.24

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by f2404** [comment]
This reminds me of https://bugzilla.xfce.org/show_bug.cgi?id=10500, can you check if the remedy posted there works for you?

**Comment by bagage** [comment]
Oh, yes it works @f2404! Hitting `Enter` + `~` + `.` quits the ssh session (I also found that [askubuntu thread](https://askubuntu.com/questions/29942/how-can-i-break-out-of-ssh-when-it-locks)). 
It's not an obvious thing though, regarding the number of upvotes for askubuntu question -- maybe Tillix could have something about that (would be awesome) or let as is (as most, if all, terminals I guess).

Anyway thanks @f2404 at least I have a proper fix now :).

**Comment by egmontkob** [comment]
I don't think there's anything terminal emulators could reasonably do here.

Terminal emulators don't "understand" what's happening inside, they basically just forward the keypresses and print whatever they're requested to print. They don't even "understand" what their immediate child, typically the shell does.

In order to detect this situation, they would need to somehow know that there's an ssh running as a grandchild, and trace what's happening inside that process. Both steps are already truly problematic, if doable at all. Furthermore, let's say the ssh client forwards the keypress to the server and doesn't receive anything back, does this really denote a problem? Maybe the user is typing a password, maybe the user is pressing a key that has no assigned function in the running app, maybe the user is trying to move/scroll in a direction where the app cannot scroll any longer, etc., and hence no update to the screen is expected to happen, how would Tilix know about it? I'm not familiar with the ssh protocol to tell whether any data is expected to come back in these cases at TCP level when a keypress is sent but no actual payload (data to be printed) is sent back.

Anyway... you might experiment with enabling keepalive in ssh. In that case ssh itself detects if the server is unreachable and exits after a certain timeout.

**Comment by gnunn1** [comment]
Thanks @f2404 and @egmontkob, as this does not appear to be a Tilix issue I'm closing.
