### ISSUE TITLE
Add Arabic support

### ISSUE THREAD

**Issue by wada3n** [gnunn1/tilix#1217]
I'm trying to write Arabic text in tilix but it does not recognize right-to-left text and does not bind the Arabic letters together as it should.
i read that tilix use vte back-end and there is no plans to implement RTL support in it!
how i can fix it?

**Comment by gnunn1** [comment]
It's up to the VTE developers to support it, there's nothing I can do about it in Tilix, sorry.

**Comment by egmontkob** [comment]
It's not that VTE just hasn't added RTL support yet or is not planning to. It's that nobody knows how to properly do BiDi in a terminal emulator. And when I say "nobody", I even mean Behdad, former VTE developer with an RTL script language as his mother tongue, as well as myself [a current VTE developer] with half a year of BiDi handling work experience. We have some thoughts about it, but not a complete picture in our minds. There's no reasonable specification anywhere, and what certain existing terminal emulators do do have their own heavy drawbacks and limitations.

Purely the logical handling of BiDi (figuring out which letter goes where) is already generally nontrivial to begin with. In terminal emulators the text arrives byte by byte as a flow, rather than suddently being there entirely; plus cursor movements and such allowed, and it's unclear how they should work in presence of RTL; plus we must remain compatible with 30-40 years of libraries and apps that don't know / don't care about BiDi at all. These make it several magnitudes more complex than let's say displaying BiDi in a graphical text editor or in a browser. And then we've only talked about deciding which character cell should contain which letter; proper shaping within a fixed-width grid is another crazy story.

I've been trying to write a document about all the thoughts I have in my mind, I'll need a couple of days(!) of free time to produce something hopefully usable that hopefully we'll be able to build on top of. I'm not sure when I'll be able to do it.

Until then, you could give [bicon](https://github.com/behdad/bicon) a try, or use a terminal emulator that does _some_ BiDi (e.g. konsole which breaks as soon as you highlight text with the mouse, or the attributes (e.g. color) change within the text; or putty's pterm or mlterm).

**Comment by egmontkob** [comment]
VTE 0.57.3 implements BiDi support (according to [this proposal](https://terminal-wg.pages.freedesktop.org/bidi/)).
