### ISSUE TITLE
Alternative to drag and drop to re-arrange terminals if I hide the title bar

### ISSUE THREAD

**Issue by Azureit** [gnunn1/tilix#1294]
Hi,
Is there any way that I don't know, alternative to drag and drop, to re-arrange terminals if I hide the title bar?

Started to use this terminal, and I like it very much and is stable. 
A Big Thanks to the developer.

regards Azure

**Comment by gnunn1** [comment]
Hold down the <ALT> key and then click to drag anywhere in the terminal.

**Comment by Azureit** [comment]
@gnunn1 which key should I hold?

**Comment by gnunn1** [comment]
The ALT key, sorry accidentally hid it with markdown formatting.

**Comment by Azureit** [comment]
@gnunn1 It isn't working that way.
Holding the ALT key and left clicking with the mouse will move the entire window.
at least with my setup: manjaro with a cinnamon desktop and the aur package tilix-git.

Most of the times, the ALT key is used to show the menu bar when it is set default hidden, like in firefox and nemo for example. If you like the idea, maybe the ALT key could be used to show the title bar when it is default hidden.

**Comment by gnunn1** [comment]
I don't have any plans to add the functionality of auto-showing the title based on a key press at this time.

**Comment by gusbemacbe** [comment]
@Azureit 

Press <kbd>Alt</kbd> + <kbd><b>Shift</b></kbd>, dragging the second Tilix window into the first Tilix window.

**Comment by bettyvschmartz** [comment]
I came here because I too have hidden the title bars. It looks cleaner IMO, but then I didn't know how to drag windows to re-arrange. I assumed there was either a keyboard shortcut to do it, or a modifier key. I went to the keyboard shortcuts dialogue but couldn't see anything. I also looked at the docs but again couldn't find anything until I landed here. 

The _alt + drag_ solution works fine for me. I'm sure there is something written somewhere about the behaviour (and maybe it's me) but would be good if this key behaviour was more visible. 

-- BVS
