### ISSUE TITLE
starting tilix in minimized quake mode

### ISSUE THREAD

**Issue by okarika** [gnunn1/tilix#1347]
Dear All,

I tried to integrate Tilix into my gnome environment by adding it to startup programs. My goal is to start in minimized and quake mode in the same time and executing my favourite backup script. 

Unfortunately I didn't find a way to achieve this, only quake mode and running a script. Is there a way to also minimize/hide the window?

I using this command to start it: tilix -q -x /home/tkovacs/backup.sh

Thanks for your help in advance

**Comment by gnunn1** [comment]
Quake mode and the concept of minimizing are not compatible, I think what you mean is to start tilix in quake mode but hidden? I don't have any plans to do that at this time.

You could run your command in a normal window which can be minimized using the ```--minimized``` flag.

**Comment by deekej** [comment]
Hello @okarika, I was actually dealing with the same issue. IMHO it is completely reasonable request you have, but since Tilix developers refuse to address, I had to come up with my own hack for this, which also includes the Wayland workaround:

```bash
#!/bin/bash

if pgrep -x 'tilix' &> /dev/null; then
  tilix --quake
else
  export GDK_BACKEND=x11
  if [[ "${1}" == '--hidden' ]]; then
    tilix --quake -e 'tilix --quake' &
  else
    tilix --quake &
  fi
fi
```
Save this small script as a `quake-terminal` in `/usr/bin` folder, and when you call it with `--hidden` option, the quake terminal will start minimized. After that you can just run `quake-terminal` to show/hide it (I suggest using some keyboard shortcut mapped to `quake-terminal` command.) Enjoy! ^_^
