### ISSUE TITLE
Widgets in Preferences are out of visible area

### ISSUE THREAD

**Issue by Mno-hime** [gnunn1/tilix#1349]
I have laptop with native 1366x768 px resolution and parts of some of the widgets in Preferences dialog are cut out of the visible area. See bottom of the screenshot.
![screenshot from 2018-03-20 19-19-15](https://user-images.githubusercontent.com/4632197/37674868-1d03d250-2c74-11e8-819f-a2a3cda69414.png)
I noticed that GNOME Tweaks has a lot of options in some tabs as well but the right side of the window is scrollable.
I use GNOME Shell 3.28.0, Tilix 1.7.7.

**Comment by egmontkob** [comment]
I can confirm this. Using the Adwaita theme, and with the new options introduced by vte-0.52, the Profile -> General tab forces an overall window height of ~755px for me. Plus gnome-shell's bar at the top -> it's too high.

Instead of making this page scrollable, probably it's better to rearrange some of the fields, e.g. move some of them to a brand new tab, or move the ID and/or Rewrap on resize to Advanced, Bold is bright to Color (this one belonged there anyway even if the window wasn't too tall)... something like these???

**Comment by gnunn1** [comment]
As @egmontkob noted the General tab is the cause of this. I think there's some easy ways to reduce the space as noted in the previous post. I'll have a look when VTE 0.52 is released on stable in Arch in a couple of weeks.

**Comment by gnunn1** [comment]
I've re-worked the dialog a bit following what gnome-terminal did and gotten the height down to 647 pixels which should fit on smaller screens. Having said that, I'd still like to come up with a cleaner design as it's just way too busy looking IMHO.

I'd love to use the new settings style but I'm not sure how it will look with all the entry widgets I have, also how much would I need to re-work on the other preference pages to achieve a holistic style.

Anyway, here's a screenshot of the revised dialog page.

![screenshot from 2018-04-02 20-59-22](https://user-images.githubusercontent.com/9358238/38223480-235071e6-36b9-11e8-9fe8-a42ffb9df206.png)

**Comment by gnunn1** [comment]
With regards to the style, I like the way gnome-builder handles it in it's preferences and it looks quite good and much busy. I'll see if I have some time over the weekend to re-work it and see how it goes.

**Comment by gnunn1** [comment]
I think for now this is fine, after considering it I'm not planning on revamping the preferences dialog dramatically in the near future.

**Comment by Mno-hime** [comment]
Thanks for fixing this @gnunn1!
