### ISSUE TITLE
CSD Header Bar Issue when title buttons aligned to left side

### ISSUE THREAD

**Issue by isacikgoz** [gnunn1/tilix#1381]
Hi,

As you can see on the screenshot, the tilix button should be placed to right side of the close, minimize and maximize buttons. It works fine if you align buttons to the right side. But there is an issue if you use like me.

![screenshot](https://user-images.githubusercontent.com/2153367/38939201-0a71a25c-4330-11e8-83b9-81fa8c82a910.png)

**Comment by gnunn1** [comment]
First, everyone knows that the min, max, close buttons go on the right and not the left :)

Seriously, can you confirm that gedit doesn't have this issue in order to rule it out as a general issue.

**Comment by isacikgoz** [comment]
![screenshot2](https://user-images.githubusercontent.com/2153367/38974072-52cba116-43b1-11e8-8092-e3f0e8001dc0.png)

**Comment by phw** [comment]
@isacikgoz There is something odd with your button setting, because gedit does not even show the app menu button at all. Usually you can configure the position of the app menu button by adding the `menu` or `appmenu` button to your button layout at the position you want.

I am a bit confused about your setup, a few questions:

1. What deskop environment are you using?
2. If using Gnome, I guess you have configured it to not show the App Menu, right?
3. Please give the output of (I am not sure whether the two settings are used in DEs other than Gnome):

    dconf read /org/gnome/desktop/wm/preferences/button-layout

    dconf read /org/gnome/shell/extensions/classic-overrides/button-layout

4. Is there a file `$HOME/.config/gtk-3.0/settings.ini` or `/etc/gtk-3.0/settings.ini`, what's the content?

In any way, if you set a button layout of `close,maximize,minimize:appmenu` the menu should show up at the very right side of the window. If you don't have the appmenu or menu entry in your button layout at all, Tilix will detect this and add it for you in order to prevent you losing access to the app menu and preferences (as it is unfortunately the case in gedit, you currently can't open its preferences dialog).

@gnunn1 The fix for Tilix should probably be to tweak the code in `force_app_menu` to detect the position of the close button and add the appmenu always to the opposite side.

**Comment by isacikgoz** [comment]
hi @phw thank you for contributing, here the answers for your questions;

1. I am using XFCE as a desktop environment
2. In window manager settings I configured not to show App Menu (Another problem with Tilix is maybe, I guess it forces to show the App Menu anyway)
3. 
```
/org/gnome/desktop/wm/preferences/button-layout is 'appmenu:close'
/org/gnome/shell/extensions/classic-overrides/button-layout #I don't have any extensions therefore I don't have such setting
```
4. There is a file `$HOME/.config/gtk-3.0/settings.ini` and it reads like below but I don't have any config file in etc
 ```
[Settings]
gtk-application-prefer-dark-theme=0
```
I configured window manager to show App Menu on the right side, it worked on other apps as exğected but on the other hand Tilix still keeps App Menu on the most left side.

**Comment by phw** [comment]
> I configured window manager to show App Menu on the right side, it worked on other apps as exğected but on the other hand Tilix still keeps App Menu on the most left side.

I don't think that worked, since gedit is also not picking up that setting.

So I have no idea how the window button layout config is saved on Xfce, and whether Gtk 3 properly loads it. But you might try setting it in `$HOME/.config/gtk-3.0/settings.ini` via:

    [Settings]
    gtk-decoration-layout=close,maximize,minimize:appmenu

**Comment by isacikgoz** [comment]
> But you might try setting it in `$HOME/.config/gtk-3.0/settings.ini` via:

I added `gtk-decoration-layout=close,maximize,minimize:appmenu` even though I restarted my pc, nothing have changed.

Maybe something related to XFCE, but I still wonder about the question: does Tilix force to show App Menu?

**Comment by phw** [comment]
> but I still wonder about the question: does Tilix force to show App Menu?

Yes it does, see my answer above. If the menu is not present in the window button layout Tilix adds it. Without this there would be no app menu at all on many systems that neither support the app menu nor set the button layout correctly.

**Comment by phw** [comment]
> Maybe something related to XFCE

Likely, but I don't know how Xfce saves the layout and whether Gtk3 can pick the config up from the Xfce settings. I found the discussion https://forum.xfce.org/viewtopic.php?id=10051 , but that only suggests the settings.ini solution you already tried.

**Comment by f2404** [comment]
Settings -> Window Manager allows to configure buttons layout in Xfce.

**Comment by isacikgoz** [comment]
> because gedit does not even show the app menu button at all.

BTW I think the App Menu on the Gedit is OK. Am I Wrong?

![peek 2018-04-19 14-59](https://user-images.githubusercontent.com/2153367/38990332-84e1ca78-43e2-11e8-8ccb-3aa40b629e89.gif)

**Comment by isacikgoz** [comment]
I tested this issue on Gnome Desktop 3.28 along with Ubuntu 18.04 beta; Close, minimize and maximize are aligned to most left side and App Menu puts right side of them. I think this issue is related with XFCE desktop environment.

**Comment by gnunn1** [comment]
@isacikgoz That's not the app menu in gedit, that's the hamburger menu. When not in the gnome environment, gedit decided to stick everything in the hamburger menu. Tilix decided to force the app menu. As I recall, there's not much consistency in this regard among the various gnome applications.

**Comment by isacikgoz** [comment]
Somehow it aligned as expected. Didn't change any settings lately, as far as I recall. 

![peek 2018-04-24 14-00](https://user-images.githubusercontent.com/2153367/39183311-3d6f7d22-47c8-11e8-95d6-a2cad3a18a60.gif)

**Comment by gnunn1** [comment]
I'm going to go ahead and close this issue, seems like it is working and I'm not willing to expend effort on testing it in xfce since I only support the Gnome DE.
