### ISSUE TITLE
Automatic Profile Switching not working at all

### ISSUE THREAD

**Issue by baptistebisson** [gnunn1/tilix#1402]
Hi.

I tried to make this functionality working but without any success. I have Tilix 1.7.7 on ubuntu 16.04 and defined a custom profile. In advanced I've created a match like this :  `baptiste-mycomputer:/home` following this [page](https://gnunn1.github.io/tilix-web/manual/profileswitch/)

But nothing happend when I'm into this folder. I found this issue : #909 
My settings are the same as the author screen.

They are talking about [triggers](https://gnunn1.github.io/tilix-web/manual/triggers/) but I don't really understand what I need to do. Any help ?

Thanks !

**Comment by gnunn1** [comment]
Is your vte configured correctly? You can tell by changing to a directory and then splitting the terminal, if the new split has the same directory as the previous one then it's working. If it opens in your home directory then it is not.

**Comment by baptistebisson** [comment]
When I split the terminal it open the home directory so my vte seem not to be configured correctly.

**Comment by gnunn1** [comment]
Sorry for the delay, I've been travelling the last couple of weeks. So I just tried this in the current version and it is working well for me. You can see how I have it configured in the screenshot below, when I open the terminal it automatically uses the Presentation profile with the larger font since that matches the expression.

If you run ```echo $HOSTNAME``` does it match what you are using? Also, if you try the match without the hostname ```:/home``` does that work?

![screenshot from 2018-05-19 09-56-45](https://user-images.githubusercontent.com/9358238/40269313-f7ee9b5c-5b4a-11e8-8b6d-610a09af5dd2.png)

**Comment by baptistebisson** [comment]
No problem !

Well it's working without hostname. `echo $HOSTNAME` do nothing for me except a new empty line in the console. Thank's !

I will now try to match a specific command like `tail -f /var/log/apache2/error.log`. I don't think that there is an easy way to match a command ?

**Comment by gnunn1** [comment]
It does not support switching on commands, just hostname, directory or username (with triggers enabled). You could do what you want by switching on the directory /var/log/apache2 and then cd to that directory followed by tailing the log. It would become a two step process though:

cd /var/log/apache2
tail -f error.log

**Comment by gnunn1** [comment]
Closing, I think this has been answered.
