### ISSUE TITLE
Shell processes do not get terminated when closing a session

### ISSUE THREAD

**Issue by f2404** [gnunn1/tilix#1409]
How to reproduce:
1. Run tilix, verify that it has spawned one shell (e.g. bash) process;
2. Open another session, verify that there are now 2 shell processes related to Tilix;
3. Close the second session.
Expected: The second shell process gets terminated.
Actual result: It keeps running.

There is no problem with opening and closing terminals within a session, shell processes are terminated in that case.

**Comment by gnunn1** [comment]
I force the vte widget to be destroyed so it gets cleaned up however it's possible I missed some combination. I suspect GC would clean it up at some point but it should behave the same everywhere.

BTW is this with tabs or sidebar?

**Comment by f2404** [comment]
With terminals, I can see a bash process disappearing immediately after I close a terminal. With sessions, I didn't see bash processes disappearing at all.

This happens with both tabs and sidebar. In sidebar mode, make sure to close a session by using "Close" from the hamburger menu and not by clicking the "x" button which closes its terminal.

**Comment by gnunn1** [comment]
OK I see the issue, back when GtkD was going through a phase of having issues dealing with some of the more complicated memory management aspects of GTK I had to comment out the explicit destruction of the session. When those issues were corrected I forgot to comment it back in again.

The commit that fixes this simply uncomments the code that was explicitly calling session.destroy. Without this the session never gets GC'ed, I suspect because various event handlers are still tied to it.
