### ISSUE TITLE
Tilix behaves oddly on kde neon

### ISSUE THREAD

**Issue by securisec** [gnunn1/tilix#1451]
I have never had any issues using Tilix in a variety of systems, until i installed the latest kde neon. 

Here is the odd behaviour where the title bar is transparent, but clickable.
![image](https://user-images.githubusercontent.com/22226823/42128193-bc013ab0-7c73-11e8-87cb-841ff3fc76fe.png)

Although i can launch the preferneces from the command line; i.e. my window mode is set to normal, i cannot click on any of the buttons.
![image](https://user-images.githubusercontent.com/22226823/42128208-06ad911c-7c74-11e8-9c16-808c9e559fc0.png)

Even the preferences window looks different
![image](https://user-images.githubusercontent.com/22226823/42128323-aa151940-7c76-11e8-95c5-4d81ee1830f7.png)

I would try updating to the latest version, and would love some instructions on how to install the release versions from github.

Thanks!

**Comment by securisec** [comment]
Playing around with GTK3 settings fixed the issue

**Comment by securisec** [comment]
On other hand, the new issue is after choosing breeze dark which makes the visual issues go away, tilix segfaults when open the preferences using either the command line or from within. 

switching back to breeze produces this error 
`Gtk-WARNING **: Theme parsing error: gtk-dark.css:1:49: Failed to import: Error opening file: No such file or director`

**Comment by gnunn1** [comment]
Note I do not support using tilix on KDE, just gnome, as I do not have the bandwidth to look into every DEs quirks and quarks.

I'm not sure what the issue is, could be you are missing the tilix resource file that it tries to load the icons from. That could also explain the transparency. If you force the Adwaita theme does it make any difference?

**Comment by securisec** [comment]
I appreciate the response. Looks like after playing around back and forth with breeze dark, the issue is mostly gone.

Thanks

**Comment by phw** [comment]
I experienced something like this in my own app Peek. The problem seems to be that the Breeze Dark GTK theme does not work as expected by GTK. And if you set your theme to Breeze and configure Tilix to prefer the dark theme it breaks with that dark.css loading error.

Try not to set the prefer dark theme option in Tilix. You can set this with dconf somehow (sorry, I can't look it up right now).

In the end I think this is a bug in the Breeze theme. I already tried to report a bug for this, but l seem to be too stupid to figure out where issues for Breeze GTK can be reported.

**Comment by securisec** [comment]
@gnunn1 would you still consider doing some documentation on how to install one of the releases? it doesnt appear to be as simple and copying over the /usr directory. thanks

**Comment by gnunn1** [comment]
There are instructions in the tilix web site, select "Manual Installation" from the list.

https://gnunn1.github.io/tilix-web/#packages

**Comment by DavidPerezIngeniero** [comment]
After upgrading to KDE Neon 18.04.1, Tilix behaves normally.
