### ISSUE TITLE
problem with two tilix instances and an open/save session dialog

### ISSUE THREAD

**Issue by nicmus** [gnunn1/tilix#1492]
The problem can be reproduced as follows

1) open tilix [first window]
2) create a new window [second window]
3) open a load or save session dialog in the second window

The terminal becomes inactive due to the dialog.
What surprises me is that also the 'other' i.e. the first window becomes inactive and keyboard input is actually captured by the dialog in the second window. I would expect that the two tilix instances are actually independent in this aspect.

**Comment by gnunn1** [comment]
I was thinking this was standard behavior for single process apps in Gnome but I see that gedit does not behave that way so I must be missing something. I'll have a look, thanks for opening a bug report for it.

**Comment by gnunn1** [comment]
The issue is that I am using run to show and handle the dialog. This should be an easy fix however I'm going to defer it until after the next release as there could be some side effects.

**Comment by gnunn1** [comment]
This has been fixed, I had to ask on the GTK channel to find the answer, turns out there is a concept of window grouping in gtk which I wasn't aware of. Modality applies to the window group rather then the window. To correct this I'm creating a new WindowGroup for every window just like gedit is doing.
