### ISSUE TITLE
Scrollback broken after ssh connection is broken in a pager

### ISSUE THREAD

**Issue by Syphdias** [gnunn1/tilix#1530]
Steps to reproduce:
1. Open tilix and produce more than one page of output in order to get a scrollback buffer (holding <Enter> should suffice)
2. Start ssh session to remote server
3. Start `vim`
4. Open another terminal and kill the ssh session
5. Try to scroll back or generate more than one page of output (in the first tilix window)

Steps to workaround this at the moment:
1. Open `vim` (or possibly any pager)
2. Quit pager

**Comment by Syphdias** [comment]
I thought this might also happen if you are in `screen` instead of a pager (Step 4), but this is handled differently

**Comment by egmontkob** [comment]
As far as Tilix itself is concerned, this is the expected behavior. Tilix (VTE) does not "understand" what's happening inside, it simply receives a series of instructions and it executes them. When you start vim, vim asks it do switch to the alternate screen that doesn't have a scrollback, and so Tilix switches. When the ssh connection breaks, no one asks Tilix to switch back. (Vim perhaps asks it when it's asked to terminate due to broken connection, but then it's already too late, this request cannot reach Tilix because, well, the connection is broken.)

As a workaround, you can execute the "reset" command, or place the escape sequence of switching back to the normal screen in your PS1 or PROMPT_COMMAND to clean up every time before printing the prompt.

**Comment by Syphdias** [comment]
So one could argue that it is a bug of the ssh client to not tell the VTE to switch back to the appropriate screen (mode)? (At least if it is killed "softly")

Also "reset" would wipe the entire scrollback history, which defeats the purpose of getting the old one back. It would probably reset the scroll behavior.

**Comment by egmontkob** [comment]
> So one could argue that it is a bug of the ssh client to not tell the VTE to switch back to the appropriate screen (mode)?

I don't think so. ssh does not know anything about the nature of the data it transmits, and IMO that should also remain this way.

The phenomenon you describe is not limited to broken ssh connections. For example, you also get stuck on the alternate screen if the application that switched there crashes for whatever reason.

IMO the most reasonable place is the shell prompt, it could perform some similar actions like turning off any colors or special attributes that might be in effect, etc.

> Also "reset" would wipe the entire scrollback history, which defeats the purpose of getting the old one back. It would probably reset the scroll behavior.

Haha, indeed, you are right, I haven't properly though it through. You can switch back to the normal screen using `echo -ne '\e[?1049l'`. If you don't feel like remembering it or quickly websearching it, just launch an app that switches to the alternate screen (e.g. `vim`) and quit it.

**Comment by Syphdias** [comment]
As much as I enjoy discussing this, you are correct in that this is not the place to fix (or discuss) this.

I couldn't test your control character, but I guess `vi +q` does the trick as well and is a bit easier to remember.

**Comment by egmontkob** [comment]
> `vi +q`

It's always great to learn something new! :) (I'm not a vi guy.)
