### ISSUE TITLE
Launch Profile 

### ISSUE THREAD

**Issue by DanitiKain** [gnunn1/tilix#1533]
I have a profile named Dropdown that I want to launch.

I launch with the command tilix -p --profile=Dropdown and it still launches that default tilix profile.  How can I specify which profile I want to launch?

**Comment by gnunn1** [comment]
Use -p or --profile not both, -p is the short version of --profile

**Comment by DanitiKain** [comment]
https://streamable.com/f6iwe

**Comment by gnunn1** [comment]
Not sure what the issue is, as it works fine on Gnome as far as I can tell and I'm sure others would be raising it as an issue if it didn't. Can you check the name you entered for Dropdown and make sure there are no leading or trailing spaces in it?

You can also try disabling DbusActivable in the desktop file and see if that makes any issues, you may want to logout/login after making that change to make sure it takes effect.

Note that I only support Gnome and not other DEs like Cinnamon so I don't do any testing on those.

**Comment by DanitiKain** [comment]
I understand you don't support other DEs.  Looks like there are no spaces.  


I am not sure how to do this part "disable DbusActivable in the desktop file" 

I looked for a tilix.desktop file and could not fine it.

**Comment by DanitiKain** [comment]
I set the DBusActivable=false and it didn't change anything.
