### ISSUE TITLE
alternate-screen.patch does not apply on VTE 0.54.1

### ISSUE THREAD

**Issue by dsboger** [gnunn1/tilix#1545]
Now that updated Fedora patches have been published, I'm trying to update vte3-tilix in AUR to 0.54.1, but the `alternate-screen.patch` is failing to apply:

```
-> Applying tilix patch
patching file src/vte/vteterminal.h
Hunk #1 succeeded at 106 with fuzz 2 (offset 2 lines).
patching file src/vtegtk.cc
Hunk #1 succeeded at 766 (offset 27 lines).
Hunk #2 succeeded at 1335 (offset 47 lines).
patching file src/vtegtk.hh
patching file src/vteinternal.hh
Hunk #1 FAILED at 1359.
1 out of 1 hunk FAILED -- saving rejects to file src/vteinternal.hh.rej
patching file src/vteseq.cc
Hunk #1 FAILED at 186.
Hunk #2 succeeded at 405 with fuzz 1 (offset -41 lines).
Hunk #3 succeeded at 440 with fuzz 1 (offset -41 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/vteseq.cc.rej
```

Thanks!

**Comment by gnunn1** [comment]
I've created a patch for the 0.54 branch of VTE however I'm having issues getting it to work with Tilix. I'm not sure if it's something I'm doing wrong in the patch or because I'm forcing make since my autotools is newer then what VTE is looking for.

The error I am getting is:

```./tilix: symbol lookup error: /home/gnunn/Development/dlang/vte/src/.libs/libvte-2.91.so: undefined symbol: _ZN3vte8platform6WidgetC1EP12_VteTerminal```

If you have a chance give it a shot and see if it works.

**Comment by dsboger** [comment]
It works for me, so I pushed 0.54.1 to AUR. Thanks again!
