### ISSUE TITLE
Per window background images

### ISSUE THREAD

**Issue by jasmith79** [gnunn1/tilix#1551]
Could we possible get per window background images (preferably set in profiles)? I don't know D or the structure of the project (i.e. whether this request is trivial or massive).

**Comment by gnunn1** [comment]
Unfortunately no. The issue is that the background is drawn at the window level whereas profiles are specific to terminals. Since it's quite possible to split two terminals with different profiles it doesn't make sense to move the preference to Profiles. There would have to be some sort of Window profile concept and I think that's just getting way too confusing.
