### ISSUE TITLE
How do I send a sequence of commands?

### ISSUE THREAD

**Issue by jonocodes** [gnunn1/tilix#1556]
Since tilix does not support scripting like tmux ala:
tmux send-keys "tail -f /vagrant/maximus.log" C-m

I'm using a session which I save and try to use:
"overrideCommand": "echo a > file1 && echo b > file2 && zsh".

But that gives an error.

I need to run a series of commands in each window pane. 

Also, for the icing on top... Lets say the overrideCommand is a process like top. If I quit the process, can I have it return to a shell somehow instead of killing that split pane?

**Comment by FFY00** [comment]
This has nothing to do with tillix. Tillix just handles the display of your shell.

**Comment by gnunn1** [comment]
There is not an easy way to do that because the intent of the specifying a command is to run it rather then the shell. You can fool around with using ```bash -c "somecommand..."``` and see if that works. You also might be able to create a script that initializes bash properly and runs a passed in command as well. You can view some thoughts on this in the following stack overflow post:

https://stackoverflow.com/questions/7120426/how-to-invoke-bash-run-commands-inside-the-new-shell-and-then-give-control-bac
