### ISSUE TITLE
Tilix Question: Regarding automatic profile switching when exiting SSH'ed server

### ISSUE THREAD

**Issue by Cumminsc9** [gnunn1/tilix#1564]
This is question regarding the feature of automatic profile switching when switching between SSH servers and the host machine.

Onto the question;
I have a couple of profiles set up 

- HOME PROFILE
- AWS PROD JUMPER PROFILE
- AWS PROD PROFILE

Home profile is for my host machine, and the other two AWS profiles are servers that I can access via SSH. On each AWS instance I have the shell alias set in `.bash_alias` as described on the Wiki page (https://github.com/gnunn1/tilix/wiki/Automatic-(Triggered)-Profile-Switching) when SSH'ing into the two AWS instances the profile changes as expected for each instance. However, when I exit the SSH instance to go back to either the host machine or the other SSH instance then the profile stays the same until I SSH back into one of the instances. 

To make that a little clearer; when exiting a SSH instance the profile does not change to the profile for that instance/machine.

I'm not sure if this is intentional, a bug, an error by my part (most likely), or if there is even a feature implemented for switching the profile back when exiting an SSH instance. I did try Googling it and searching through past issues to see if anyone else had the same query but I couldn't find any results. However, my current understanding is that if the HOME PROFILE automatic switch has been set up to match the `host:directory` then the profile should change when the SSH instance is closed and I am returning to the host machines shell.

Can someone help in clearing this up, because I may have the wrong end of the stick or a configuration incorrect somewhere, and If anyone needs any more details, screenshots or examples just ask and I can provide.

**Comment by gnunn1** [comment]
If you could post a screenshot of your configuration that would be helpful. Also note that the automatic profile changing reacts to changes, in your case the host name, but it does not reset conditions as it is trigger based not condition based. So if you have profile setting configured for the AWS machines and the exit, it won't reset because there hasn't been a trigger. You would need to add a switch to use the home profile when on the home machine for it to trigger back when exiting.
