### ISSUE TITLE
No alert when ctrl-s suspends console I/O

### ISSUE THREAD

**Issue by crgithubmoth** [gnunn1/tilix#1593]
Tilix needs a door hanger or whatever you can click to resume, should say 
Console suspended by ctrl-s (or ~)
See konsole

**Comment by egmontkob** [comment]
On a side note, are you aware of `stty ixany`? This will make any key restart the output.

I'm not sure what Konsole exactly does, but it doesn't do it quite right. E.g. if I configure `stty stop ^A` then it still warns me when I press `^S` (which no longer locks), but doesn't warn me if I press `^A` (which locks now). On the other hand, when running an app that disables this feature, it properly doesn't warn, so it's more sophisticated than just looking for the `^S` keypress.

[VTE 755371](https://bugzilla.gnome.org/show_bug.cgi?id=755371) implemented tracking the scroll lock state robustly, even when nondefault keys are chosen. In this regard it's better than Konsole. Alas, the work got stalled halfway and we ended up not using this info for anything.

Ideally that work should be continued, either to change the cursor shape which would immediately work in all VTE-based emulators, or to notify the terminal app which could then do whatever it wants to.

It's unclear to me at this moment whether Tilix on its own (without help from VTE) could do something more or less reasonable, e.g. similar to what Konsole does.

**Comment by gnunn1** [comment]
I don't think this is something Tilix can do without having more insight into the state of the terminal. At the moment there is no way for Tilix to know whether certain keys are pressed to perform a terminal wide action (i.e. ctrl-s to suspend I/O) or as input to an application.

I'm closing this since there is nothing I can do to resolve it, if VTE adds the required functionality I'm happy to re-open it.
