### ISSUE TITLE
/GException.d(41): PCRE2 not supported

### ISSUE THREAD

**Issue by denisgolius** [gnunn1/tilix#1622]
```
dengolius@think /tmp $ sudo tilix
[sudo] password for dengolius: 
glib.GException.GException@../../../.dub/packages/gtk-d-3.8.4/gtk-d/generated/gtkd/glib/GException.d(41): PCRE2 not supported
```

```
dengolius@think /tmp $ uname -a
Linux think 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
dengolius@think /tmp $ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
```
UBUNTU_CODENAME=bionic

**Comment by gnunn1** [comment]
This is a bug with Ubuntu, they need to patch Tilix everytime there is a new release. See #916 for more information.

**Comment by denisgolius** [comment]
* What is VTE?

VTE is a library (libvte) implementing a terminal emulator widget for GTK+,
and a minimal sample application (vte) using that.  Vte is mainly used in
gnome-terminal, but can also be used to embed a console/terminal in games,
editors, IDEs, etc.

So why is used VTE ? It's seem like developers start to use bad lib :-1:

**Comment by egmontkob** [comment]
VTE developers are not responsible for Ubuntu applying patches that break cross-component dependencies. Please complain at Ubuntu.

**Comment by gnunn1** [comment]
There wouldn't be a Tilix without VTE, writing a terminal emulator is surprisingly difficult to get right given the sheer amount of legacy baggage that needs to be supported. Fortunately GNOME had the foresight to package the terminal emulation for gnome-terminal has a widget which makes it easy for lot's of applications to include it. Terminator, GNOME Builder, Guake, etc all leverage VTE.

As @egmontkob pointed out, Ubuntu broke VTE when they patched it to remove PCRE2 functionality but left the version number exactly the same. This means that applications on Ubuntu that use VTE have no way of knowing this feature has been removed since VTE doesn't identify it. This means that Ubuntu has to patch any application leveraging VTE to fix this including terminator, gnome-builder, etc.

While I respect their rights to make that call, frankly my opinion is that this was a bad decision. At the end of the day though this was Ubuntu's call and thus they are responsible for managing it. As @egmontkob  noted any complaints about this should be directed at Ubuntu.

**Comment by denisgolius** [comment]
😕 Time to replace Ubuntu by Debian... Thank you :)

**Comment by egmontkob** [comment]
Ubuntu's Tilix and VTE packages work together well because they are both patched. Or you can replace both of them with unpatched versions. Or you can stay with Ubuntu's VTE, and manually patch the Tilix you install yourself, it'll also work. That is, you have at least three options to get Tilix that don't require replacing your OS. Of course, switching to Debian is another possibility, it's up to you.
