### ISSUE TITLE
[Proposal] Drop Sidebar functionality in favor of tabs

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/tilix#1627]
I am thinking about dropping the sidebar in Tilix and just go all in on tabs. While the sidebar is neat, it has a number of complexities with it's implementation to make it work. Those complexities lead to bugs which are often hard to track down, for example a small memory leak that I've mitigated but haven't been able to eliminate.

Additionally, going all in on tabs would make the code much cleaner and make it easier to implement additional functions, for example the UI design work that is being done in #1541.

I'm therefore requesting feedback from the community before I remove this functionality.

**Comment by phw** [comment]
>     * it does not occupied any screen space; on the opposite I think that tab are a waste of space and reduce the useful vertical size on 16:9 / 16:10 screens

This is exactly why I use the sidebar as well. I don't like the tabs very much. On the other hand I personally don't use the sidebar itself very often, so for me having the option to hide the tabs would probably work as well (which means using only the keyboard shortcuts). But I still would like to see the number of the current session and the session counter which the current sidebar button provides.

If the sidebar causes too much code trouble maybe providing a simpler session switcher popover would be an alternative? You could still make tabs the default if this better suits the majority of users.

**Comment by syedelec** [comment]
Personally a sidebar user for the same reasons as above.

**Comment by cprog** [comment]
Sidebar is unique . I like it so much for the same reasons as above.

**Comment by ConorPFarrell** [comment]
I'm in the same camp as @trongthanh - as an ex-iTerm2 user, personally, I don't like the sidebar model purely because it doesn't let me easily see what sessions I have open. I don't want to have to click something to find that out.

**Comment by mjourdan** [comment]
As I understand it, the issue with the sessions sidebar has more to do with the thumbnails than with the sidebar itself, right? Stupid question: in the future, could something like Pipewire provide real-time sessions preview, instead of pixbuf?

I think an overview is absolutely required for who manages dozens of terminals across several sessions. Tabs (alone) do net give enough information. The sidebar provides one more clue, the session layout, but still it is sometimes hard to distinguish between sessions. Hence the use of colors in some mockups shown in #1541, which do use the sidebar.

@trongthanh @ConorPFarrell If you do use a pointing device, a single click more over tabs doesn't seem a bad tradeoff. But if a single click is absolutely too much, you can keep your hands on your keyboard and open/close the sidebar using F12. 

Yet, it is certainly true that either sidebar or tabs should be dropped. Maybe even both could be replaced with something else.

**Comment by aaronSkar** [comment]
I'm ok ditching the side bar for tabs.  The side bar is cool but tabs are just as easy to navigate so long as they are able to have custom names.

**Comment by edubxb** [comment]
I really love the tab-less interface (to save some pixels), but I'm use the keyboard to change between sessions, so a tab interface with the option to hide it will be enough for me.

Although the session sidebar preview is really a cool feature.

**Comment by Daemoen** [comment]
I guess im in a very different group than most people here -- I would actually like an option for *normal* 'vertical' tabs..  While realizing that this would seem like a 'waste' of screen space to some, when you only work in maximized sessions anyway, it isn't a big impact.  additionally, i dont particularly need the tiling in the emulator due to using tmux....  vertical tabs are *much more* readable (again -- 'normal' vertical tabs -- the session name/title is horizontal, not vertical)

**Comment by gnunn1** [comment]
Thanks everyone for the input, I think I'm just going to leave things as the status quo for now.
