### ISSUE TITLE
Preferences Windows doesn't respect CSD setting

### ISSUE THREAD

**Issue by ifohancroft** [gnunn1/tilix#1640]
Even with CSD disabled, the preferences window still uses CSD.

**Comment by gnunn1** [comment]
The CSD options only apply to the main window, I do not plan to apply them across all windows in Tilix like preferences, bookmarks, various dialogs etc. 

This is because Tilix is intended to be a gnome application, while I did add the CSD options to help out folks not on gnome I don't want to carry it to lesser used windows as options have a maintenance cost associated with them.
