### ISSUE TITLE
Q/FR: Bottom Space/Margin in Tilix

### ISSUE THREAD

**Issue by daniel-wtd** [gnunn1/tilix#1648]
I am facing the situation, that Tilix has some margin/space in each terminal at the bottom.

This has the impact, that some tools cannot use this space and will look somewhat "off".
The screenshot shows a typical screen hardstatus and the prompt, which will never "use" the bottom space.

Have I missed an option to configure this? If not, I would open this as a feature request.

![screenshot from 2019-02-12 15-08-58](https://user-images.githubusercontent.com/6490538/52641073-5d060500-2ed8-11e9-9946-cc383b43d169.png)
![screenshot from 2019-02-12 15-09-55](https://user-images.githubusercontent.com/6490538/52641074-5d060500-2ed8-11e9-95dc-5733e636d433.png)

**Comment by gnunn1** [comment]
The tilix window can be resized to the pixel level whereas VTE only displays to the nearest column and row. Tilix needs to behave this way because of the tiling, it would be extremely difficult to have all of the tiles align correctly on row, column boundaries. Since gnome-terminal does not have tiling it does not need to worry about this.

I do not have any plans to change this behavior.

**Comment by daniel-wtd** [comment]
@gnunn1 Thank you for the detailed explanation.

Keep up the good work! :+1:
