### ISSUE TITLE
Remove powerline from the screenshots

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [gnunn1/tilix#1656]
Please remove screenshots showing the powerline prompt from your main page.

This is IMO kind of pretense. Lot of people try your Tilix because of this awesome looking terminal. But it isn't yours.

**Comment by gnunn1** [comment]
I don't see this as an issue personally, it's showing exactly how I have my terminal configured. I don't see it as any different to showing a screenshot with fish or zsh instead of bash

**Comment by egmontkob** [comment]
+1 for gnunn'1 comment.

You can't take a screenshot of Tilix without showing the artwork of a GTK+ theme. You can't show any inner content without showing a certain font too, again someone else's work. Plus, in order to show a real life example, you'd also have to rely on some popular utility, e.g. "ls" developed by someone else, including its coloring configuration added by yet another someone, and the corresponding color palette, which may or may not be Tilix's own creation (I'm not sure), showing the contents of a directory which looks like a SSG template, yet another someone's work. At this point it's already easily 5-6 or so different sources other than Tilix itself, and IMO it's fine, it's absolutely fine. I see no problem with also displaying powerline, oh-my-zsh, or whatever these screenshots happen to have – unless the license of one of such components forbids such use, which I doubt is the case here.

**Comment by Dan1jel** [comment]
I downloaded Tilix because of the good looking theme. Didn't get that, so i asked about it, didn't get that either, uninstalled. If i could get the theme, i (or others) would maybe try it because here is were you see it. But fooling others to see something that's not there seems a little fishy.

**Comment by jeffdyke** [comment]
I would second @Dan1jel , i'm sure i'll have the fonts running in a minute, its worth a readme.  b/c it works in all other shells (ubuntu 20.04), the fonts and styles are not being rendered the path is correct.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I find the maintainers attitude against the users and the work of other projects very interesting.

**Comment by jeffdyke** [comment]
Not sure why i got the down vote, was just being honest, and the fix is partially in Tilix.    I'll submit a PR, but b/c i was determined to not let this go as i really like your project.  But here for posterity and any google searches.  Ensure the following:
```
git clone https://github.com/powerline/fonts.git && cd fonts && sh ./install.sh
```
Then in **Preferences -> Default -> Custom Font** and in the drop drop down search for `powerline` and choose the one that suits you, it will refresh without the need to open a new window.

**Comment by Dan1jel** [comment]
It dose say then the faq:

"Where is the option to get the cool colored prompts like in the screenshots?

That comes from powerline and is not something Tilix provides."

And that's great, but for me when i saw the photo on the Tilix page, i thought it looked like that, and i really like the color settings for Powerline. But after the disappointment without the theme, and i had do start looking, i found the info on FAQ page. 

I just think that photo is misleading. But that's my opinion.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> the fix is partially in Tilix.

This tells me that you do not disagree with me and @Dan1jel but you still do not understand the problem itself.

Breath. Take your time and read again:
**New users entering your project site seeing that screenshot think that Tillix is able to offer that nice colored (powerline) prompt.**

This results in frustrated new users: They install Tillix, see it does not work and throw it away. You waste time of your potential users!

Second you disrespect the work of the powerline-project. You even do not refere to the powerline project bellow that screenshot. Think about juristic consequences also.

**Comment by Dan1jel** [comment]
> > the fix is partially in Tilix.
> 
> This tells me that you do not disagree with me and @Dan1jel but you still do not understand the problem itself.
> 
> Breath. Take your time and read again:
> **New users entering your project site seeing that screenshot think that Tillix is able to offer that nice colored (powerline) prompt.**
> 
> This results in frustrated new users: They install Tillix, see it does not work and throw it away. You waste time of your potential users!
> 
> Second you disrespect the work of the powerline-project. You even do not refere to the powerline project bellow that screenshot. Think about juristic consequences also.
> 
> Please try to step out your dev-thinking-zone and try to think like your users.

No I'm with you all the way, i think either they should share the setting/color config or change tilis phots to something else that dont show powerline.

So I'm with you to 100%

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> No I'm with you all the way

:D I know. It was not for you @Dan1jel. My message was addressed to  @jeffdyke.

**Comment by jeffdyke** [comment]
@Codeberg-AsGithubAlternative-buhtz I honestly don't know what you're trying to prove/say.  I saw that someone was having a similar problem, came up with a solution and asked that a PR be accepted to show it to others.  In my mind that would solve it for others.  I saw the FAQ, doesn't mean i don't want to help people improve the expierence.  I have nothing against either project and I AM the user, not the dev, you keep responding like i'm the author of one of these great projects.
