### ISSUE TITLE
[Feature Request] random color scheme change

### ISSUE THREAD

**Issue by gnurichard** [gnunn1/tilix#1678]
Sometimes, when you have several terminals open, it is difficult to distinguish one from the other. It could be useful, to have the option that, each new session can take a different color scheme, randomly from the ones we have installed, to distinguish them quickly, while we navigate through the windows

**Comment by gnunn1** [comment]
Interesting idea but I don't think I want to add this as a feature at this time as I don't think it's something most people would use. Thanks for the suggestion.

**Comment by egmontkob** [comment]
Assuming #1455 gets fixed, you can do it by emitting OSC 10 & 11 escape sequences from your shell's startup files (e.g. `.bashrc` or `.zshrc`).

Instead of random, you could also make the colors deterministic based on the tty line number (the output of the `tty` command). I used to do it.

You might also take a look at pending [gnome-terminal issue 142](https://gitlab.gnome.org/GNOME/gnome-terminal/issues/142). Not sure if we'll complete that work; if we do then it'll be easily available for Tilix too.
