### ISSUE TITLE
Disable font ligatures

### ISSUE THREAD

**Issue by pauwell** [gnunn1/tilix#1743]
Hi.
I started using `Dank Mono` as my font in tilix yesterday and then started realising, that the ligatures are messed up.
Is it currently not possible to disable ligatures or am I just blind. 

Thanks in advance, Paul.

**Comment by gnunn1** [comment]
VTE, the terminal emulator widget that tilix uses, doesn't support fonts with ligatures.

**Comment by egmontkob** [comment]
VTE 0.50 and older series had problems with fonts that defined ligatures, e.g. the `>` symbol showed up incorrectly if there was a ligature for `=>` defined in the font, or something along these lines. This was fixed in version 0.52.

That being said, ligatures are indeed not supported by VTE, these characters show up one by one.
