### ISSUE TITLE
Some color emojis are broken in tilix

### ISSUE THREAD

**Issue by Titubery** [gnunn1/tilix#1782]
Such as 🧜🏻‍♀️ or 👨‍👩‍👦‍👦 :
![emjs](https://user-images.githubusercontent.com/17917040/67863533-0b350600-fb5f-11e9-9cef-89358d66153a.png)
I've tried that in `bash` and `fish` with `ttf-joypixels`. Those emojis are rendered perfectly in other places except terminals. It also messes up  `tab` auto-completion.

**Comment by egmontkob** [comment]
GitHub seems to mangle the second of your emojis somehow, at least it can't be copy-pasted from the rendered page, but it can be from the page source.

Looks like these emojis are:
U+1F9DC MERPERSON
U+1F3FB EMOJI MODIFIER FITZPATRICK TYPE-1-2
U+200D ZERO WIDTH JOINER
U+2640 FEMALE SIGN
U+FE0F VARIATION SELECTOR-16

and

U+1F468 MAN
U+200D ZERO WIDTH JOINER
U+1F469 WOMAN
U+200D ZERO WIDTH JOINER
U+1F466 BOY
U+200D ZERO WIDTH JOINER
U+1F466 BOY

It's unclear to me why you don't have the female sign showing up, and why you have two skin tone modifiers showing up. That's not what I get in Tilix, I get one skin tone modifier character and one female sign. To be on the safe side, could you confirm that this is the exact Unicode sequence you're operating with, or even better: attach a text file and a screenshot of `cat`ing it? Also please make sure that you have VTE version >= 0.56.

Anyway:

The problem is with the U+200D ZERO WIDTH JOINER character that is completely ignored by VTE, not doing any joining. It looks easily fixable, except for two issues: it'll take up the same amount of space as now, e.g. 8 character cells for the family with four members (practically impossible to change to two cells); and it'll be broken across a linebreak (cumbersome to fix).

Could you please open a new issue at https://gitlab.gnome.org/GNOME/vte/issues, including the list of Unicode codepoints, or a demo file attached, as mentioned above; and close this one here? It needs to be fixed in VTE, there's nothing Tilix could do about it.

**Comment by egmontkob** [comment]
Something like this...

[vte-tilix1782-zwj-and-skin-tones.patch.txt](https://github.com/gnunn1/tilix/files/3791398/vte-tilix1782-zwj-and-skin-tones.patch.txt)

**Comment by Titubery** [comment]
Thanks.
