### ISSUE TITLE
[Feature request] Switch to rust

### ISSUE THREAD

**Issue by CountOmega** [gnunn1/tilix#2104]
If tilix were to be rewritten in Rust, it would probably attract more maintainers. This is related to #1700; because I feel like very few people know D. Also, the GTK bindings for Rust have definitly improved. I know this is a ton to ask for, especially as there is little active development. As far as I know there isn't a d to rust transpiler which would ease a (possible) transition. Also in regards to #1700: GNOME is embracing Rust and has already quite a few Rust applications and Rust developers (e.g. @bilelmoussaoui ).
I'm not advocating that tilix needs to be rewritten, I just think it would gain more popularity that way and (possibly) more maintainers/developers.

**Comment by yookoala** [comment]
With all due respect, switching language basically means a complete rewrite of the software. Anybody can freely do that as another project and it doesn't even need to named "Tilix".

Besides, since there is currently no active maintainer to the project, nobody can do any rewrite / development on it. If there is anybody who is willing to do so, there wouldn't be a lack of maintainer in the first place.

**Comment by wyatt-herkamp** [comment]
@CountOmega lol. Funny thing. I was today wondering if I could install tilix on Windows. Then I was wondering about doing a tilix like terminal in Rust. That is cross platform

**Comment by CountOmega** [comment]
@yookoala @wyatt-herkamp I agree. I'm not "demanding" a rewite. If someone did a rewrite of Tilix in Rust it'd be cross-platform and (probably) more popular
