### ISSUE TITLE
Broken character encoding format

### ISSUE THREAD

**Issue by Revel109** [gnunn1/tilix#2121]
![image](https://user-images.githubusercontent.com/22530100/192250186-71bb4bf0-4624-463d-89fd-0299c53ae174.png)

Device: ubuntu-20.04 LTS
tilix version: latest

**Comment by 237dmitry** [comment]
In my opinion, this is a font settings problem. Exactly the same occurs if I uncheck "Custom font" in the profile settings. In `~/.config/fontconfig/fonts.conf` as a monospaced font set `Note Sans Mono` but this font is not installed.

![ArcoLinux_2022-09-27_00-32-08](https://user-images.githubusercontent.com/78153320/192385264-302cefcd-4b3e-4b4f-9daa-164894439230.png)

![ArcoLinux_2022-09-27_00-34-28](https://user-images.githubusercontent.com/78153320/192385302-1d80fb36-b8ce-48cb-bf1f-0b39b6625011.png)

**Comment by Revel109** [comment]
Unchecked but no luck :(

**Comment by 237dmitry** [comment]
> Unchecked but no luck :(

If "Custom Font" is unchecked you have to check font settings in your Desktop Environment. There are must be a set of default fonts. For example in XFCE:
![ArcoLinux_2022-09-27_19-13-47](https://user-images.githubusercontent.com/78153320/192579719-bb959ba1-16e6-4787-8927-b578e559089c.png)

It could be so that field with font name is empty or with non-installed font.

**Comment by Revel109** [comment]
I had to rollback Monospace text to Monospace Regular
It was SF Pro Display Regular earlier
Solved finally

![image](https://user-images.githubusercontent.com/22530100/193073649-a6ce807c-1d93-4ac2-a5c1-ea424cc4c1bf.png)
