### ISSUE TITLE
Feature Request:  Drag terminal to different session

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/tilix#281]
It would be great if dragging the terminal onto the session sidebar button on the top left would pop it open and let you drop it into a different (or new) session.

**Comment by gnunn1** [comment]
Unfortunately I don't see an easy way to open the sidebar while the drag is happening.

**Comment by stuaxo** [comment]
Is there no way to know if the drag is over the session button, so it could then open?

**Comment by gnunn1** [comment]
@stuaxo Maybe, I'm not sure it would be possible to pop-open the revealer while a drag is occuring. However, even if that worked how do you close it again so you can drop it on a terminal underneath? 

The other aspect is that I'm still looking at re-working the sidebar, I don't want to expend a ton of effort on use cases which are challenging until I know what I'm doing on that front. Unfortunately, this one fits into that category. I've closed this issue since there is a perfectly valid way of accomplishing the same task, albeit with slightly more effort.

**Comment by stuaxo** [comment]
Makes sense :)
