### ISSUE TITLE
The notification disappears almost immediately.

### ISSUE THREAD

**Issue by simonbcn** [gnunn1/tilix#436]
For some time, the notifications, when a command has finished, disappears almost immediately. In first versions, it worked well.

**Comment by gnunn1** [comment]
Nothing has changed with this code as far as I can tell, I believe how long the notification is displayed for is up to your desktop environment (DE) not Terminix as I'm not setting this anywhere AFAIK. On my system the notification shows for the same amount of time it always has.

What distro and desktop environment are you using, has anything been upgraded lately?

**Comment by simonbcn** [comment]
Arch Linux 64 bits
GNOME Shell 3.20.3

How long a notification is displayed depends on several factors in Gnome Shell: https://developer.gnome.org/notification-spec/

I will test previous versions of Terminix to detect where the change occurred. Or perhaps it's an error in `vte3-notification` package (_AUR package_).

**Comment by gnunn1** [comment]
@simonbcn Any luck with your tests, can this be closed?

**Comment by simonbcn** [comment]
I haven't tested it. I've uninstalled Terminix.

**Comment by simonbcn** [comment]
```
Arch Linux
GNOME Shell 3.28.2

$ tilix --version
Versions
	Tilix version: 1.8.1
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=1
	Badges enabled=1
```

This error still occurs.

**Comment by gnunn1** [comment]
I cannot reproduce this, from the tilix point of view I'm just sending a notification to gnome and I have no control over the timeout of the notification on that side. So I'm not seeing how this is a tilix problem.

If you try the gnome terminal on Arch that has notification support, gnome-terminal-fedora, does it have the same issue or does it work fine?

**Comment by gnunn1** [comment]
Thanks, I think there is room for improvement here but I wonder if part of the issue is that command you are using executes relatively quickly. Tilix will only show a notification when the window doesn't have notification and the will withdraw when it receives focus again. With opening a different window maybe there is a timing issue.

What happens if you do ```sleep 20``` in tilix, switch to a different window and then wait. Does the notification last until you switch back to tilix?

As an aside for me, I think I need to look at the uuid I'm using to identify notifications. Right now everything goes out on the appwindow uuid which means there can only ever be one notification per window. I think I should be using the terminalUUID instead for these similar to what fedora terminal is using.

**Comment by simonbcn** [comment]
It seems the problem is the execution time. With `sleep 20` it works.
But if Tilix has the notification support, it should alert me at the end of any command if it is not in focus. Because otherwise I'll never know when it's gonna notify me and when it's not.

**Comment by gnunn1** [comment]
I've updated the code to send notifications on a per terminal basis rather then application. I don't have any plans to add notification support for terminals which are visible but not in focus when the tilix application window has focus, I don't think that's useful. When the application window does not have focus you will see notifications.
