### ISSUE TITLE
Help with shortcut

### ISSUE THREAD

**Issue by akyag** [gnunn1/tilix#831]
I have a launcher shortcut that executes the command as follows - 

> [Desktop Entry]
> Comment=
> Terminal=true
> Name=Sonarr
> Exec=mono /home/akya/NzbDrone/NzbDrone.exe
> Type=Application
> Icon=/home/akya/My Icons/Sonarr.png
> Name[en_US]=Sonarr

but this opens the default terminal. Adding /usr/bin/terminix before mono doesn't work either. I want this launcher to execute in terminix too and not open the regular terminal.
I am on Fedora 25 x64 btw.

**Comment by vmercuri** [comment]
Like gnome-terminal, Tilix (former Terminix) supports the ``-e`` option, which lets you execute a parameter (a "string", in this case) as a command. You need to configure your ```Sonarr.desktop``` file with something along the line of:

```
[Desktop Entry]
Type=Application
Exec=terminix -e "mono ..."
Terminal=false
...
```
Also, don't forget to make it executable with ```chmod +x Sonarr.desktop```.

**Comment by gnunn1** [comment]
@vmercuri provided a great answer, however here's an alternate workaround to make Tilix the default browser. First some background, if you look at the Gnome bug https://bugzilla.gnome.org/show_bug.cgi?id=627943 you can see the issue is that glib hard-codes the terminal emulators. 

Comment 55 (https://bugzilla.gnome.org/show_bug.cgi?id=627943#c55) on the bug report provides an easy way to make tilix the default terminal emulator by symlinking it as ```gnome-terminal``` in a bin directory that appears in your $PATH before ```/usr/bin```. In Arch Linux, I created a gnome-terminal symlink as follows:

```
sudo ln -s /usr/bin/tilix /usr/local/bin/gnome-terminal
```
Keep in mind though that after this change the gnome-terminal launcher will launch tilix instead of gnome-terminal. If you want to keep the gnome-terminal launcher working correctly, you will need to modify it to point explicitly to ```/usr/bin/gnome-terminal```.
