### ISSUE TITLE
Cursor color resets to default after changing any other color in the Color Palette

### ISSUE THREAD

**Issue by vmercuri** [gnunn1/tilix#885]
Build from master, Fedora 25/26-alpha, Xorg. In Preferences->Default->Color->Options->Advanced, change your cursor background color to any color, then modify any other color in the "Color Palette" (Background/Foreground included). You should notice that the cursor color switches back to the default. The workaround is to change the cursor color last (and everytime any other color is modified).

**Comment by gnunn1** [comment]
I think this is a bug in VTE, the reason that gnome-terminal doesn't have this issue is because it always updates all the colors even when just one changes. Tilix on the other hand treats colors more granularity only updates the color that changes. In the VTE it looks like changing any color on it's own causes the cursor color to reset.

I'll need to work around this by either doing the same or updating the cursor color manually after modifying other colors.

**Comment by gnunn1** [comment]
I've opened this bug against VTE:

https://bugzilla.gnome.org/show_bug.cgi?id=781369

**Comment by vmercuri** [comment]
Thanks, I'll keep an eye on that.

**Comment by gnunn1** [comment]
I've pushed a workaround that always sets the cursor color after setting foreground, background or palette color.

**Comment by vmercuri** [comment]
Much appreciated. Tilix is a wonderful terminal, it fits particularly well in my daily workflow. I wish it was the default terminal in Gnome. Keep up the good work.
