### ISSUE TITLE
ubuntu budgie migration path from terminix to tilix

### ISSUE THREAD

**Issue by fossfreedom** [gnunn1/tilix#906]
Hi,
  Ubuntu 17.10 has just updated to Tilix 1.5.4 via a sync with Debian.

As you know, Ubuntu Budgie 17.04 included terminix.  The name change is causing us an issue now due to the vteconfig dialog appearing.  For 17.04 we had to apply the `ln -s /etc/profile.d/vte-2.91.sh /etc/profile.d/vte.sh` and then via a /etc/skel/.bashrc apply the `if [[ $TERMINX_ID ]]; then source /etc/profile.d/vte.sh; fi` so that new accounts automatically get the necessary changes to make terminix work out of the box.

I note in https://gnunn1.github.io/tilix-web/manual/vteconfig/ that there is a second workaround to choose the "login shell" option.  I don't really understand what this option is - but it does appear to fix the issue for debian/ubuntu.

I would like to apply a gsettings override so that it is checked by default so that there is a smooth upgrade path from terminix to tilix - unfortunately this is defined in a relocatable schema so it only applies in userspace - not at install time.

Could I ask - what does this login shell option?  Any side effects for ticking this option?

If there are no side effects - can I ask that the next version of tilix either enables this option by default - or provide another non relocatable key that distro packages such as myself can override - if the key is enabled then enable the "login shell" option on its schema & key creation.

**Comment by egmontkob** [comment]
Allow me please to chime in... I'm not a Tilix developer; I'm a VTE / GNOME Terminal developer, and used to develop Linux distributions too.

The problems you're facing actually point much deeper than where you're looking.

One thing is that the Tilix rename already happened significantly before 17.04's release and Ubuntu folks were aware of that. They really should not have introduced a brand new package under an obsolete name, just to face unnecessary troubles with the renaming later on. 17.04 should have shipped Tilix.

Second thing is that in VTE we have like 2 or 3 bugreports about refactoring `vte.sh` to address all the known issues (including making this one a non-issue), and the fact that Ubuntu's and other distro's developers repeatedly fail to adhere to our (mainstream's) guidance keeps setting back on our motivation to address these. Ideally Ubuntu, Fedora etc. devs would cooperate with VTE devs coming up with the right solution (which would probably be shipping `/etc/bashrc.d/vte-2.91.sh` and making `/etc/bashrc` source all scripts under `/etc/bashrc.d`.

Third,

> via a /etc/skel/.bashrc [...] so that new accounts automatically get the necessary changes to make terminix work out of the box

I really don't get it. Did you, like, seriously, think at one point "hey, this Terminix is a cool new piece of software, let's ship it, and let's make it work flawlessly for new users... but existing users, ney, we don't care about them"???

I actually still cannot understand why `/etc/skel` hasn't died a terrible death decades ago. See e.g. https://bugzilla.gnome.org/show_bug.cgi?id=697475.

Trying to solve anything from `/etc/skel` is doomed to fail, and you should stop doing that this very moment. Any solution should go to global config files (e.g. do the one I recommended with `/etc/bashrc.d` above).

> Could I ask - what does this login shell option?

Please refer to the shell's manual page.

> Any side effects for ticking this option?

Some folks might not like it (e.g. I don't). It might cause stuff to be printed when a new terminal is opened, might cause problems if someone's `.profile` is not idempotent, etc.

Let alone that just because you tick an option, a user is free to untick it and the software should still work. No piece of software should ever ship a config option that goes like "do you want me to work correctly or not?".

> provide another non relocatable key

In the unlikely case that the project needs to be renamed again, all the keys will relocate, there's just no way to prevent that. Nobody expected that to happen to the Terminix name.

**Comment by fossfreedom** [comment]
@egmontkob Thanks for the feedback.

I really can't comment about terminix vs tilix.  Ubuntu Budgie is working with what was available at the time.

Anyway, thanks for the idea about /etc/bashrc.d.  In Ubuntu that file doesnt exist but probably the equivalent is /etc/bash.bashrc

So to the solution is I suppose to append to /etc/bash.bashrc the statement `if [ $TILIX_ID ] || [ $VTE_VERSION ]; then  source /etc/profile.d/vte.sh; fi` ?

N.B. I can clean up the /etc/skel stuff easy enough.

**Comment by fossfreedom** [comment]
actually ... probably better to add a .sh file to /etc/profile.d since bash runs through .sh files there.

**Comment by gnunn1** [comment]
I'm late to the game but I think @egmontkob answered this pretty thoroughly, is there anything I need to provide?

**Comment by gnunn1** [comment]
Oh and please note if you haven't already that user's will lose their settings unless you migrate them as part of the package upgrade. Tilix will not re-load the old Terminix settings automatically.

There are instructions on how to do this on the main README.md.

**Comment by fossfreedom** [comment]
Hi - yeah - I'm kind of at a rock and a hard place here. Ubuntu (debian?) doesnt source anything under /etc/bashrc.d and I'm not in any influential position to make fedora and ubuntu come up with a common position :(

So rather stuck here as to the best way forward.  Any suggestions?

**Comment by fossfreedom** [comment]
ok - I've worked around it for now - I'll use a script in /etc/profile.d to put stuff in .bashrc if required. That means I can remove the /etc/skel stuff.

I'll leave the boxing match between fedora and debian/ubuntu to sort things out properly.

**Comment by gnunn1** [comment]
@fossfreedom Does ubuntu actually source /etc/profile.d? I thought this was the problem with VTE on Ubuntu, it was one of the distributions that did not?

https://askubuntu.com/questions/438150/scripts-in-etc-profile-d-being-ignored

**Comment by fossfreedom** [comment]
@gnunn1 I'm mulling over at the moment of using a shell script in source /etc/profile.d which is run on logon and that script appends the vte source command to ~/.bashrc - that way (I think) that is executed (sourced or whatever the phrase is) when Tilix is run.

**Comment by gnunn1** [comment]
Oh now I understand. Can't say I'm a fan of that approach though, I don't think modifying .bashrc is a good idea as there are too many ways for things to go wrong. i.e. How do you know it's been inserted previously, what if the user tweaks the inserted bit that causes it to no longer be detected, etc.

**Comment by fossfreedom** [comment]
@gnunn1 at the moment the script grep's .bashrc for a known string "terminx_id ... #ubuntu budgie" and if it cant find it it inserts the necessary string.  Yeah - I'm not a fan either.  But given that Debian/Ubuntu doesnt allow bash to source external scripts like Fedora does, I'm not sure what other way is possible.  I would love to just insert into /etc/bashrc or whatever its called but obviously that will be overwritten by package updates.
