### ISSUE TITLE
Problem making Automatic (Triggered) Profile Switching to work

### ISSUE THREAD

**Issue by rabin-io** [gnunn1/tilix#909]
After reading though the wiki about [Automatic (Triggered) Profile Switching](/gnunn1/tilix/wiki/Automatic-(Triggered)-Profile-Switching) and going over issue #135 , I still can't make it to work. 

I'm running fedora/25 with MATE DE, Tilix installed from [my repo](https://build.opensuse.org/package/show/home:rabin-io/tilix) based on the spec file from heikoada/terminix copr repository.

![screenshot4](https://cloud.githubusercontent.com/assets/5116363/25681957/f6adc00a-305e-11e7-80d3-fa055abac373.png)

any help ?

**Comment by gnunn1** [comment]
You need to define a trigger to extract the username from the login prompt in order to support switching based on username. Triggers require a patched VTE which I don't believe you have. The documentation (https://gnunn1.github.io/tilix-web/manual/profileswitch/) mentions this:

> Note that switching profiles based on username requires the use of a trigger to extract the username from the terminal output text.
 
The docs should make this more obvious, I'll update it.

**Comment by gnunn1** [comment]
Actually minor bug here too, the code shouldn't let you define the user portion without triggers being available. I'll have a look at that as well.

**Comment by gnunn1** [comment]
I've modified the code to disallow the ```@``` token unless VTE has the trigger feature enabled.
