### ISSUE TITLE
Feature: Save state and restore

### ISSUE THREAD

**Issue by deepu105** [gnunn1/tilix#928]
HI first of all thanks for the awesome terminal EMU. Its the best I have used so far and I'm loving it.

If tilix could periodically save the save the state(The position, size and directory of each tile) of all the open sessions into an a hidden config file and restore all the sessions when the app is opened it would be great(Like how chrome works). It will help in following scenarios:

- System crash, shutdown from low battery from sleep
- System upgrades etc

Such an option would let us close and open Tilix without having to worry about loosing the state of each session.

Im aware of the save session and open config options. They are nice but they are not the best in terms of usability as you need to save each session individually and restore it individually. The above behaviour would be awesome in terms of usability.

**Comment by gnunn1** [comment]
I'm not keen on this mostly because beyond the layout the important bits of the state can not be saved. For example, ssh connections in different window, running programs, history for each shell, etc. Thus any sort of solution of this is would be somewhat half-baked at best.

Additionally, since tilix is a single process all windows would need to be saved as well and under Wayland restoring window position isn't possible which again means a half baked solution at best.

As a result I don't think I will be pursuing this idea. However I do want to say thank you for taking the time to make the suggestion, I do appreciate it.

**Comment by deepu105** [comment]
Thanks for the response. Just to clarify when I said state I didnt mean all
these aspect actually I wS talking about juat the layout and directory of
all sessions. Same s how the individual json export works now but instead
of manual save, auto save all sessions to a json and restore.

If thats not feasible atleast an option to save all sessions into with a
single command would be nice

On 15 May 2017 3:04 am, "Gerald Nunn" <notifications@github.com> wrote:

I'm not keen on this mostly because beyond the layout the important bits of
the state can not be saved. For example, ssh connections in different
window, running programs, history for each shell, etc. Thus any sort of
solution of this is would be somewhat half-baked at best.

Additionally, since tilix is a single process all windows would need to be
saved as well and under Wayland restoring window position isn't possible
which again means a half baked solution at best.

As a result I don't think I will be pursuing this idea. However I do want
to say thank you for taking the time to make the suggestion, I do
appreciate it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gnunn1/tilix/issues/928#issuecomment-301353353>, or mute
the thread

**Comment by martin-g** [comment]
See my solution at https://github.com/gnunn1/tilix/issues/99#issuecomment-318327720

**Comment by mfilipen** [comment]
Hi. I think it will be a great feature.

My use case:
1. I usually use 10 tabs, with a special layout for each.
2. I understand which part of the screen is responsible for what.
3. Furthermore, I use history (arrow up) to rerun some script and after do Ctrl + C.
4. The reboot is always a pain since I need to type all commands. (sometimes I use gedit to save history).

Thanks!

**Comment by vgjenks** [comment]
Any hope of reviving this concept? Been using iTerm2 on a Mac for a couple of years and Tilix is the closest analogue on desktop *nix. This is really the one big missing killer feature that iTerm does better. Manually saving and restoring sessions is a pain and easy to forget. We're often working out of several tabs with several tiles, and this would be a massive improvement.
