### ISSUE TITLE
"Unfocused dim" functionality changed in 1.5.8

### ISSUE THREAD

**Issue by brittyazel** [gnunn1/tilix#939]
With the update to 1.5.8 on Archinux using the Tilix-bin package, the "Unfocused dim" functionality seems to have changed from a direct dimming of the window, to now the window taking on whatever is set as the "foreground" color whenever it is out of focus. This resulted in my first opening of tilix after the update being presented with a bright green command window every time I did anything that put it out of focus, and it took me a while to figure out what was going on.

I'm not sure I love this new way of handling unfocused dimming, as now my window actually changes its color each time focus is moved elsewhere, instead of just "dimming" as the feature suggests. 

Further, while it appears that under the "advanced" tab in the color window allows you to toggle on a checkbox for "dim" with a specific color, whenever you hit the checkbox "Use theme colors for foreground/background" that dropdown box becomes unclickable, thus forcing the above issue unless I want to make or use one of the main color schemes.

Anyway, this whole "unfocused dim" thing has gotten a whole lot more complicated all of a sudden, and I'm not opposed to changing this feature, but it isn't very intuitive as it stands now.

**Comment by gnunn1** [comment]
See #900 for discussion on this issue. Frankly if someone has a good idea to make it work well across the board for all theme/color combinations I'm all ears. As it stands now it looks pretty challenging to make this work well for everybody.

I'm really starting to despise this feature :)

**Comment by phw** [comment]
To be honest I also don't quite like the new behavior, but I workaround it by setting a custom dim color.

But as @brittyazel pointed out, I too find the color options here a bit confusing. I don't understand why  the advanced colors (cursor, highlighting, dimming) can only be set if the option to use theme colors for background/foreground is disabled. I'd rather keep using the theme colors, but still set a separate dim color.

In the end I also would prefer a black default, as @dsboger said on https://github.com/gnunn1/tilix/issues/900#issuecomment-303909465 . But obviously no default will make everybody happy. I think the current behavior is quite similar to what iTerm2 does. In the end I don't care much as long as I can easily change it, so I think the "advanced colors not being available unless you disable to use theme colors for forground/background" is the real issue here.

**Comment by gnunn1** [comment]
I've committed a change to enable the advanced colors all the time. Since each one has a toggle to indicate whether or not to use it I'm not remembering why I tied it to the system theme colors. Please try it out and let me know if this addresses the concerns.

I'll spend some time thinking about how the default dimming color should work as well.

**Comment by phw** [comment]
@gnunn1 Now the advanced colors are available all the time, but the dim color from advanced still is only applied, when "use theme color" is disabled.

The colors for cursor and badge work however independent of the "use theme color" setting (not sure about highlight and bold, didn't test).

**Comment by gnunn1** [comment]
@phw Thanks for testing, I've added a commit to correct that issue so it should work now.

**Comment by gnunn1** [comment]
So I've prototyped doing it similarly to terminators method which is to darken the font. In this scenario the dim color would be removed and the slider controls the percentage to darken the font. I've attached a screenshot below, I think I'm going to go this way unless anyone has a major obhection to it?

Dark background:

![screenshot from 2017-06-17 19-57-07](https://user-images.githubusercontent.com/9358238/27257060-66d94542-5397-11e7-951b-7f961344d3f6.png)

Light background:

![screenshot from 2017-06-17 20-08-07](https://user-images.githubusercontent.com/9358238/27257108-c1a68556-5398-11e7-8bd6-b6fb2ff6d41a.png)

**Comment by gnunn1** [comment]
I've checked in this change, feel free to play with it and let me know what you think. If there's major issues or discontent with it I can always revert the commit.

**Comment by gnunn1** [comment]
No one is complaining about the new way of handling dim so I'm closing this issue. Any future issues or questions feel free to re-organizing this.

**Comment by rightaway** [comment]
The screenshots you've posted look great, but when I set Unfocused Dim all that happens is that some of the colors in the color palette I selected get dimmed appropriately, but all remaining colors stay exactly the same. I've set the color palette using dconf.

**Comment by phw** [comment]
@rightaway Working here as expected. If this does not work for you, you should probably open a new issue and provide some more details (screenshot, the actual color palette you are using).
