### ISSUE TITLE
Split a terminal when it is maximised

### ISSUE THREAD

**Issue by kaustubhhiware** [gnunn1/tilix#967]
It should be possible to split a terminal when I have maximised it. When unmaximised, the full screen and the split terminals could be fit into the size of the original terminal before it was maximised.

**Comment by gnunn1** [comment]
I do not have any plans to support this as it doesn't make sense to me. The concept of maximizing is to view a single terminal filling the space, once you split it what's that mode become? Do both terminals show restore buttons instead of maximize in the titlebar? It just becomes very confusing IMHO

Additionally from a programming point of view it would be messy.
