### ISSUE TITLE
Can this dumb white line at the top of borderless and fullscreen terminals please be removed?

### ISSUE THREAD

**Issue by hobbledehoy899** [gnunn1/tilix#988]
It seems serves no purpose and makes otherwise fashionable borderless and fullscreen terminals look bad.

![what point](https://user-images.githubusercontent.com/29778895/27692966-aaed1816-5cad-11e7-9a69-c1473321a420.png)

**Comment by gnunn1** [comment]
What desktop environment and GTK theme are you using? Is the white line there if you use Adwaita as the theme?

**Comment by gnunn1** [comment]
Oh sorry I see Cinnamon in the screenshot, is it the default theme? I'd still appreciate if you try Adwaita as a comparison point.

**Comment by hobbledehoy899** [comment]
It looks the exact same with Adwaita, no difference made

**Comment by gnunn1** [comment]
I don't see the issue on my machine, here's a screenshot:

![screenshot from 2017-06-29 21-39-36](https://user-images.githubusercontent.com/9358238/27717521-d88b7c84-5d13-11e7-9871-0037a0fea6cd.png)

Please note that I don't officially support Cinnamon, I only support Gnome and Ubuntu in terms of reproducing issues as it's just too much effort dealing with all of the Linux DEs out there. Having said that< I suspect your issue may be related to the version of GTK that is being used.

Can you paste the output of ```tilix --version``` so I can see what version of GTK you are using. Here's mine on Arch Linux:

```
[gnunn@gnunn-xps15 ~]$ tilix --version
Versions
	Tilix version: 1.6.2-0.0.1
	VTE version: 0.48
	GTK Version: 3.22.16

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=1
	Badges enabled=1
```

**Comment by hobbledehoy899** [comment]
Versions
```
	Tilix version: 1.6.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0

```

**Comment by hobbledehoy899** [comment]
```
Versions
	Tilix version: 1.6.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
I cannot duplicate this under Ubuntu 16.04 as per the screenshot below. I tried setting the GTK theme to Adwaita in case that was it but no luck. Maybe it could be the Cinnamon shell theme that is causing this issue?

![screenshot from 2017-07-02 10-52-05](https://user-images.githubusercontent.com/9358238/27770908-0d54d4f8-5f15-11e7-8b64-b64fb8ade698.png)


Anyway, as mentioned I don't support Cinnamon and I've gone as far as I'm willing to in order to track this down. If you can reproduce it in an environment I support feel free to re-open the issue and I'll have a look again.
